name: tasker
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  image_picker:
  image_cropper: ^1.4.0
  pin_code_fields: ^7.4.0
  url_launcher:
  fluttertoast: ^8.0.9
  flutter_launcher_icons:
  flutter_share:
  shared_preferences:
  intl:
  provider:
  skeletons:
  font_awesome_flutter: ^10.6.0
  country_code_picker_x: ^2.0.5
  hijri:
  jhijri_picker: ^1.0.1
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  dotted_border:
  jhijri: ^1.0.0
  syncfusion_flutter_charts: ^23.1.42
  dio:
  http:
  path_provider:
  permission_handler:
  rename:
  awesome_number_picker: ^0.0.4
  flutter_bloc:
  file_picker:
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
flutter_icons:
  image_path_android: "assets/images/logoapp.png"
  android: true
  image_path_ios: "assets/images/logoapp.png"
  ios: true

flutter:


  uses-material-design: true

  #الصور
  assets:
    - assets/images/
    - assets/icons/
  #الفونت الخط
  fonts:
    - family: ArefRuqaa
      fonts:
        - asset: assets/fonts/ArefRuqaa-Bold.ttf

    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
